export type Company = {
  id: number
  name: string
  stars: string
  starsNum: number
  price: string
  tag: 'Emergency' | 'Book ahead'
  tagEs: string
  desc: string
  descEs: string
  warranty: string
  warrantyEs: string
  expertRating: number
  googleRating: number
  googleReviews: number
  phone: string
  website: string
}

export const companies: Company[] = [
  {
    id: 1,
    name: 'Chicago Roof Masters',
    stars: '★★★★★',
    starsNum: 5,
    price: 'from $350',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: 'Since 2005 · Storm & leak specialist · Free estimate',
    descEs: 'Desde 2005 · Especialista en tormentas y goteras · Presupuesto gratuito',
    warranty: 'Warranty: 5 years on labor',
    warrantyEs: 'Garantía: 5 años en mano de obra',
    expertRating: 4.9,
    googleRating: 4.8,
    googleReviews: 132,
    phone: '3120000000',
    website: '#',
  },
  {
    id: 2,
    name: 'WindCity Roofing',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $280',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: 'Best price in the city · Flat & pitched · Free estimate',
    descEs: 'Mejor precio en la ciudad · Techos planos e inclinados · Presupuesto gratuito',
    warranty: 'Warranty: 2 years on labor',
    warrantyEs: 'Garantía: 2 años en mano de obra',
    expertRating: 4.7,
    googleRating: 4.7,
    googleReviews: 98,
    phone: '3120000001',
    website: '#',
  },
  {
    id: 3,
    name: 'ProRoof Chicago',
    stars: '★★★★★',
    starsNum: 5,
    price: 'from $450',
    tag: 'Book ahead',
    tagEs: 'Reservar',
    desc: 'Commercial & residential · Licensed & insured',
    descEs: 'Comercial y residencial · Con licencia y seguro',
    warranty: 'Warranty: 10 years on labor & materials',
    warrantyEs: 'Garantía: 10 años en mano de obra y materiales',
    expertRating: 4.6,
    googleRating: 4.9,
    googleReviews: 114,
    phone: '3120000002',
    website: '#',
  },
  {
    id: 4,
    name: 'Lakeside Roofing Co.',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $320',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: 'Full replacements · All Chicago neighborhoods',
    descEs: 'Reemplazos completos · Todos los barrios de Chicago',
    warranty: 'Warranty: 3 years on labor',
    warrantyEs: 'Garantía: 3 años en mano de obra',
    expertRating: 4.5,
    googleRating: 4.6,
    googleReviews: 87,
    phone: '3120000003',
    website: '#',
  },
  {
    id: 5,
    name: 'Storm Shield Roofing',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $400',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: 'Storm damage specialists · Insurance claim help',
    descEs: 'Especialistas en daños por tormenta · Ayuda con reclamaciones de seguro',
    warranty: 'Warranty: 5 years on labor & materials',
    warrantyEs: 'Garantía: 5 años en mano de obra y materiales',
    expertRating: 4.4,
    googleRating: 4.5,
    googleReviews: 76,
    phone: '3120000004',
    website: '#',
  },
  {
    id: 6,
    name: 'Anchor Point Roofing',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $380',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: '5+ years · Free estimates · On-site service',
    descEs: '5+ años · Presupuestos gratuitos · Servicio en sitio',
    warranty: 'Warranty: 1 year on labor',
    warrantyEs: 'Garantía: 1 año en mano de obra',
    expertRating: 4.4,
    googleRating: 4.9,
    googleReviews: 244,
    phone: '3120000005',
    website: '#',
  },
  {
    id: 7,
    name: 'Midwest Roofing',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $300',
    tag: 'Book ahead',
    tagEs: 'Reservar',
    desc: '20+ years · All Chicago areas · Flat & pitched',
    descEs: '20+ años · Todas las áreas de Chicago · Planos e inclinados',
    warranty: 'Warranty: 2 years on labor',
    warrantyEs: 'Garantía: 2 años en mano de obra',
    expertRating: 4.3,
    googleRating: 4.9,
    googleReviews: 219,
    phone: '3120000006',
    website: '#',
  },
  {
    id: 8,
    name: 'Reliable Roofing',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $350',
    tag: 'Emergency',
    tagEs: 'Emergencia',
    desc: '30+ years · 24/7 service · Free estimate',
    descEs: '30+ años · Servicio 24/7 · Presupuesto gratuito',
    warranty: 'Warranty: 5 years on labor',
    warrantyEs: 'Garantía: 5 años en mano de obra',
    expertRating: 4.3,
    googleRating: 5.0,
    googleReviews: 49,
    phone: '3120000007',
    website: '#',
  },
  {
    id: 9,
    name: 'Chicago Flat Roof Services',
    stars: '★★★★☆',
    starsNum: 4,
    price: 'from $420',
    tag: 'Book ahead',
    tagEs: 'Reservar',
    desc: '25+ years · Flat roof specialist · Online estimate',
    descEs: '25+ años · Especialista en techos planos · Presupuesto en línea',
    warranty: 'Warranty: 3 years on labor & materials',
    warrantyEs: 'Garantía: 3 años en mano de obra y materiales',
    expertRating: 4.2,
    googleRating: 4.9,
    googleReviews: 71,
    phone: '3120000008',
    website: '#',
  },
  {
    id: 10,
    name: 'Budget Roof Fix',
    stars: '★★★☆☆',
    starsNum: 3,
    price: 'from $200',
    tag: 'Book ahead',
    tagEs: 'Reservar',
    desc: 'Most affordable · Best for minor repairs',
    descEs: 'Más asequible · Ideal para reparaciones menores',
    warranty: 'Warranty: 1 year on labor',
    warrantyEs: 'Garantía: 1 año en mano de obra',
    expertRating: 3.8,
    googleRating: 4.1,
    googleReviews: 34,
    phone: '3120000009',
    website: '#',
  },
]

export const MAIN_PHONE = '3120000000'
export const MAIN_PHONE_DISPLAY = '(312) 000-0000'
export const EMAIL = 'roofrepairchicagonow@gmail.com'
