export type Service = {
  slug: string
  name: string
  title: string
  metaDescription: string
  intro: string
  bodyText: string
  faq: { q: string; a: string }[]
  nameEs: string
  titleEs: string
  metaDescriptionEs: string
  introEs: string
  bodyTextEs: string
  faqEs: { q: string; a: string }[]
}

export const services: Service[] = [
  {
    slug: 'flat-roof-replacement',
    name: 'Flat Roof Replacement',
    title: 'Flat Roof Replacement Chicago',
    metaDescription: 'Flat roof replacement in Chicago. TPO, EPDM, and modified bitumen specialists. Licensed contractors, free estimates, written warranties.',
    intro: 'Flat roofs are the most common roof type in Chicago on two-flats, three-flats, courtyard buildings, and commercial properties. When a flat roof fails, replacement is almost always more cost-effective than repeated repairs. Our verified contractors specialize in flat roof replacement with all major membrane systems.',
    bodyText: 'A flat roof replacement in Chicago costs $8,000 to $20,000 for most residential buildings, depending on square footage and membrane system chosen. TPO membrane is the current code-preferred system in Chicago. It reflects heat, handles Chicago freeze-thaw cycles well, and typically carries a 15 to 20 year manufacturer warranty. EPDM rubber is common on older buildings and is often used when budget is a priority. Modified bitumen is sometimes chosen for commercial applications or where a torch-applied system is preferred. The replacement process involves removing the old membrane down to the decking, inspecting and replacing any damaged insulation or decking boards, installing new insulation to meet current energy code requirements, and applying the new membrane system. A City of Chicago building permit is required for flat roof replacement. All contractors on our list pull permits as part of the project.',
    faq: [
      { q: 'How much does flat roof replacement cost in Chicago?', a: 'Flat roof replacement on a Chicago two-flat typically runs $8,000 to $14,000 for a TPO system. Larger buildings cost more. EPDM systems cost slightly less. All contractors offer free on-site estimates.' },
      { q: 'What flat roof system is best for Chicago?', a: 'TPO membrane is the most commonly specified flat roof system in Chicago. It performs well in cold winters, reflects summer heat, and is code-compliant. EPDM is a proven alternative. Avoid BUR systems on new installations as they are less energy-efficient.' },
      { q: 'How long does a new flat roof last in Chicago?', a: 'A properly installed TPO or EPDM flat roof lasts 20 to 30 years in Chicago with annual inspections and minor maintenance. Modified bitumen systems last 15 to 20 years. Chicago winters are harder on flat roofs than pitched roofs due to standing water and freeze-thaw stress.' },
      { q: 'Do I need a permit for flat roof replacement in Chicago?', a: 'Yes. The City of Chicago requires a building permit for flat roof replacement. Contractors on our list include permit costs in their contracts and pull the permit before work begins.' },
    ],
    nameEs: 'Reemplazo de Techo Plano',
    titleEs: 'Reemplazo de Techo Plano en Chicago',
    metaDescriptionEs: 'Reemplazo de techo plano en Chicago. Especialistas en TPO, EPDM y betún modificado. Contratistas con licencia, presupuestos gratuitos, garantías escritas.',
    introEs: 'Los techos planos son el tipo de techo más común en Chicago en edificios de dos y tres pisos, edificios de patio y propiedades comerciales. Cuando un techo plano falla, el reemplazo casi siempre es más rentable que las reparaciones repetidas. Nuestros contratistas verificados se especializan en el reemplazo de techos planos con todos los principales sistemas de membrana.',
    bodyTextEs: 'Un reemplazo de techo plano en Chicago cuesta entre $8,000 y $20,000 para la mayoría de los edificios residenciales, dependiendo de los metros cuadrados y el sistema de membrana elegido. La membrana TPO es el sistema actualmente preferido por el código en Chicago. Refleja el calor, maneja bien los ciclos de congelación-descongelación de Chicago y generalmente tiene una garantía del fabricante de 15 a 20 años. El caucho EPDM es común en edificios más antiguos y se usa frecuentemente cuando el presupuesto es una prioridad. El betún modificado a veces se elige para aplicaciones comerciales o donde se prefiere un sistema aplicado con soplete. El proceso de reemplazo implica retirar la membrana vieja hasta el tablero, inspeccionar y reemplazar el aislamiento o tableros dañados, instalar nuevo aislamiento para cumplir con los requisitos actuales del código de energía y aplicar el nuevo sistema de membrana. La Ciudad de Chicago requiere un permiso de construcción para el reemplazo de techo plano. Todos los contratistas de nuestra lista obtienen los permisos como parte del proyecto.',
    faqEs: [
      { q: '¿Cuánto cuesta el reemplazo de techo plano en Chicago?', a: 'El reemplazo de techo plano en un edificio de dos pisos de Chicago cuesta típicamente entre $8,000 y $14,000 para un sistema TPO. Los edificios más grandes cuestan más. Los sistemas EPDM cuestan un poco menos. Todos los contratistas ofrecen presupuestos gratuitos en sitio.' },
      { q: '¿Qué sistema de techo plano es mejor para Chicago?', a: 'La membrana TPO es el sistema de techo plano más comúnmente especificado en Chicago. Funciona bien en inviernos fríos, refleja el calor del verano y cumple con el código. El EPDM es una alternativa probada. Evite los sistemas BUR en instalaciones nuevas ya que son menos eficientes energéticamente.' },
      { q: '¿Cuánto dura un techo plano nuevo en Chicago?', a: 'Un techo plano de TPO o EPDM correctamente instalado dura de 20 a 30 años en Chicago con inspecciones anuales y mantenimiento menor. Los sistemas de betún modificado duran de 15 a 20 años. Los inviernos de Chicago son más duros para los techos planos que para los techos inclinados debido al agua estancada y el estrés de congelación-descongelación.' },
      { q: '¿Necesito un permiso para el reemplazo de techo plano en Chicago?', a: 'Sí. La Ciudad de Chicago requiere un permiso de construcción para el reemplazo de techo plano. Los contratistas de nuestra lista incluyen los costos del permiso en sus contratos y obtienen el permiso antes de comenzar el trabajo.' },
    ],
  },
  {
    slug: 'asphalt-shingle-replacement',
    name: 'Asphalt Shingle Replacement',
    title: 'Asphalt Shingle Roof Replacement Chicago',
    metaDescription: 'Asphalt shingle roof replacement in Chicago. Architectural and impact-resistant options. Licensed contractors, free estimates, 5 to 10 year warranties.',
    intro: 'Asphalt shingles are the most common roofing material on Chicago single-family homes and bungalows. When shingles reach 20 years or show widespread granule loss, cracking, or curling, full replacement is more cost-effective than repeated repairs. Our verified contractors install architectural shingles from leading manufacturers with strong warranty coverage.',
    bodyText: 'Asphalt shingle replacement in Chicago costs $8,000 to $16,000 for most single-family homes depending on square footage, pitch, and shingle grade. Standard architectural shingles run $9 to $13 per square foot installed. Class 4 impact-resistant shingles cost $1 to $2 more per square foot but often qualify for insurance premium discounts that pay back the difference over time. The replacement process involves removing all existing shingle layers down to the decking, inspecting decking for rot or damage, installing Ice and Water Shield membrane at eaves and valleys as required by Chicago code, adding synthetic underlayment over the full deck, and installing new shingles with proper fastening pattern for Chicago wind loads. Most residential shingle replacement projects in Chicago are completed in one day. All contractors on our list offer free estimates and pull the required City of Chicago building permit.',
    faq: [
      { q: 'How much does asphalt shingle replacement cost in Chicago?', a: 'Full asphalt shingle replacement on a typical Chicago home runs $8,000 to $16,000 depending on roof size and shingle grade. Most homes fall between $9,000 and $13,000. Free on-site estimates available from all listed contractors.' },
      { q: 'How long do asphalt shingles last in Chicago?', a: 'Standard 3-tab shingles last 15 to 20 years in Chicago. Architectural shingles last 20 to 25 years. Chicago freeze-thaw cycles and hot summers shorten lifespan compared to manufacturer ratings. Class 4 impact-resistant shingles perform better and sometimes last 25 to 30 years.' },
      { q: 'What is the difference between 3-tab and architectural shingles?', a: '3-tab shingles are thinner, lighter, and less expensive. They have a flat appearance and are rated for lower wind speeds. Architectural shingles are thicker, heavier, and have a dimensional appearance. They carry longer warranties and perform better in Chicago winters. Most contractors recommend architectural shingles for Chicago homes.' },
      { q: 'Should I get Class 4 impact-resistant shingles in Chicago?', a: 'Class 4 impact-resistant shingles cost 10 to 15 percent more than standard architectural shingles. Many homeowner insurance policies in Illinois offer discounts for Class 4 roofs. Ask your insurance agent before your roof replacement to calculate whether the upgrade pays back through reduced premiums.' },
    ],
    nameEs: 'Reemplazo de Techo de Tejas de Asfalto',
    titleEs: 'Reemplazo de Techo de Tejas de Asfalto en Chicago',
    metaDescriptionEs: 'Reemplazo de techo de tejas de asfalto en Chicago. Opciones arquitectónicas y resistentes al impacto. Contratistas con licencia, presupuestos gratuitos, garantías de 5 a 10 años.',
    introEs: 'Las tejas de asfalto son el material de techado más común en las casas unifamiliares y bungalows de Chicago. Cuando las tejas alcanzan los 20 años o muestran pérdida generalizada de gránulos, agrietamiento o curvatura, el reemplazo completo es más rentable que las reparaciones repetidas. Nuestros contratistas verificados instalan tejas arquitectónicas de los principales fabricantes con amplia cobertura de garantía.',
    bodyTextEs: 'El reemplazo de tejas de asfalto en Chicago cuesta entre $8,000 y $16,000 para la mayoría de las casas unifamiliares según los metros cuadrados, la inclinación y el grado de teja. Las tejas arquitectónicas estándar cuestan entre $9 y $13 por pie cuadrado instaladas. Las tejas resistentes al impacto Clase 4 cuestan entre $1 y $2 más por pie cuadrado, pero a menudo califican para descuentos en primas de seguro que recuperan la diferencia con el tiempo. El proceso de reemplazo implica retirar todas las capas de tejas existentes hasta el tablero, inspeccionar el tablero en busca de pudrición o daños, instalar membrana Ice and Water Shield en los aleros y valles según lo requiere el código de Chicago, agregar sub-membrana sintética sobre todo el tablero e instalar tejas nuevas con el patrón de fijación adecuado para las cargas de viento de Chicago. La mayoría de los proyectos residenciales de reemplazo de tejas en Chicago se completan en un día. Todos los contratistas de nuestra lista ofrecen presupuestos gratuitos y obtienen el permiso de construcción requerido por la Ciudad de Chicago.',
    faqEs: [
      { q: '¿Cuánto cuesta el reemplazo de tejas de asfalto en Chicago?', a: 'El reemplazo completo de tejas de asfalto en una casa típica de Chicago cuesta entre $8,000 y $16,000 según el tamaño del techo y el grado de teja. La mayoría de las casas están entre $9,000 y $13,000. Presupuestos gratuitos en sitio disponibles de todos los contratistas de la lista.' },
      { q: '¿Cuánto duran las tejas de asfalto en Chicago?', a: 'Las tejas estándar de 3 solapas duran de 15 a 20 años en Chicago. Las tejas arquitectónicas duran de 20 a 25 años. Los ciclos de congelación-descongelación de Chicago y los veranos calurosos acortan la vida útil en comparación con las calificaciones del fabricante. Las tejas resistentes al impacto Clase 4 tienen mejor desempeño y a veces duran de 25 a 30 años.' },
      { q: '¿Cuál es la diferencia entre tejas de 3 solapas y arquitectónicas?', a: 'Las tejas de 3 solapas son más delgadas, ligeras y económicas. Tienen una apariencia plana y están clasificadas para velocidades de viento más bajas. Las tejas arquitectónicas son más gruesas, pesadas y tienen una apariencia dimensional. Tienen garantías más largas y funcionan mejor en los inviernos de Chicago. La mayoría de los contratistas recomiendan tejas arquitectónicas para las casas de Chicago.' },
      { q: '¿Debo obtener tejas resistentes al impacto Clase 4 en Chicago?', a: 'Las tejas resistentes al impacto Clase 4 cuestan entre un 10 y un 15 por ciento más que las tejas arquitectónicas estándar. Muchas pólizas de seguro de propietario en Illinois ofrecen descuentos para techos Clase 4. Consulte con su agente de seguros antes del reemplazo del techo para calcular si la mejora se recupera a través de primas reducidas.' },
    ],
  },
  {
    slug: 'metal-roof-replacement',
    name: 'Metal Roof Replacement',
    title: 'Metal Roof Replacement Chicago',
    metaDescription: 'Metal roof replacement in Chicago. Standing seam and metal shingle options. Long-term value, licensed contractors, free estimates.',
    intro: 'Metal roofing is the longest-lasting option for Chicago homes. A properly installed metal roof lasts 40 to 70 years and requires minimal maintenance. Our verified contractors install standing seam and metal shingle systems on residential and commercial buildings throughout Chicago.',
    bodyText: 'Metal roof replacement in Chicago costs $15,000 to $30,000 for most single-family homes depending on system type and roof complexity. Standing seam metal roofing costs $15 to $22 per square foot installed and is the premium option. Metal shingles that mimic the look of asphalt or slate cost slightly less. Metal roofs perform exceptionally well in Chicago winters. They shed snow without forming ice dams, unlike asphalt shingles where snow accumulation and freeze-thaw cycles cause granule loss. Metal roofing is also fire-resistant and wind-resistant up to 140 mph. The higher upfront cost is offset by the 40 to 70 year lifespan compared to 20 to 25 years for asphalt. For homeowners planning to stay in their home long term, metal is often the better long-term investment.',
    faq: [
      { q: 'How much does metal roof replacement cost in Chicago?', a: 'Metal roof replacement on a typical Chicago home runs $15,000 to $28,000 for standing seam systems. Metal shingles cost slightly less. Free on-site estimates from all listed contractors.' },
      { q: 'Is metal roofing worth the extra cost in Chicago?', a: 'For homeowners planning to stay in their home 15 or more years, metal roofing typically provides better long-term value than asphalt. The 40 to 70 year lifespan means one replacement versus two or three asphalt replacements over the same period.' },
      { q: 'Does metal roofing handle Chicago winters better than asphalt?', a: 'Yes. Metal roofs shed snow efficiently and do not develop ice dams the way asphalt shingle roofs do. They also expand and contract with temperature changes without cracking or losing granules.' },
      { q: 'How noisy is a metal roof in rain?', a: 'Modern metal roofing installed over solid decking with underlayment is not significantly louder than asphalt. The hollow sound associated with metal roofs applies to older barn-style installations, not residential standing seam systems on solid decks.' },
    ],
    nameEs: 'Reemplazo de Techo de Metal',
    titleEs: 'Reemplazo de Techo de Metal en Chicago',
    metaDescriptionEs: 'Reemplazo de techo de metal en Chicago. Opciones de costura alzada y tejas de metal. Valor a largo plazo, contratistas con licencia, presupuestos gratuitos.',
    introEs: 'El techado de metal es la opción más duradera para los hogares de Chicago. Un techo de metal correctamente instalado dura de 40 a 70 años y requiere un mantenimiento mínimo. Nuestros contratistas verificados instalan sistemas de costura alzada y tejas de metal en edificios residenciales y comerciales en todo Chicago.',
    bodyTextEs: 'El reemplazo de techo de metal en Chicago cuesta entre $15,000 y $30,000 para la mayoría de las casas unifamiliares según el tipo de sistema y la complejidad del techo. El techado de metal de costura alzada cuesta entre $15 y $22 por pie cuadrado instalado y es la opción premium. Las tejas de metal que imitan la apariencia del asfalto o la pizarra cuestan un poco menos. Los techos de metal funcionan excepcionalmente bien en los inviernos de Chicago. Eliminan la nieve sin formar diques de hielo, a diferencia de las tejas de asfalto donde la acumulación de nieve y los ciclos de congelación-descongelación causan pérdida de gránulos. El techado de metal también es resistente al fuego y al viento hasta 140 mph. El mayor costo inicial se compensa con la vida útil de 40 a 70 años en comparación con los 20 a 25 años del asfalto. Para los propietarios que planean quedarse en su hogar a largo plazo, el metal suele ser la mejor inversión a largo plazo.',
    faqEs: [
      { q: '¿Cuánto cuesta el reemplazo de techo de metal en Chicago?', a: 'El reemplazo de techo de metal en una casa típica de Chicago cuesta entre $15,000 y $28,000 para sistemas de costura alzada. Las tejas de metal cuestan un poco menos. Presupuestos gratuitos en sitio de todos los contratistas de la lista.' },
      { q: '¿Vale la pena el costo adicional del techado de metal en Chicago?', a: 'Para los propietarios que planean quedarse en su hogar durante 15 años o más, el techado de metal generalmente proporciona un mejor valor a largo plazo que el asfalto. La vida útil de 40 a 70 años significa un reemplazo versus dos o tres reemplazos de asfalto durante el mismo período.' },
      { q: '¿El techado de metal maneja mejor los inviernos de Chicago que el asfalto?', a: 'Sí. Los techos de metal eliminan la nieve de manera eficiente y no desarrollan diques de hielo como los techos de tejas de asfalto. También se expanden y contraen con los cambios de temperatura sin agrietarse ni perder gránulos.' },
      { q: '¿Qué tan ruidoso es un techo de metal bajo la lluvia?', a: 'El techado de metal moderno instalado sobre un tablero sólido con sub-membrana no es significativamente más ruidoso que el asfalto. El sonido hueco asociado con los techos de metal se aplica a instalaciones antiguas de estilo granero, no a sistemas residenciales de costura alzada sobre tableros sólidos.' },
    ],
  },
  {
    slug: 'tpo-epdm-roof-replacement',
    name: 'TPO / EPDM Roof Replacement',
    title: 'TPO and EPDM Flat Roof Replacement Chicago',
    metaDescription: 'TPO and EPDM flat roof replacement in Chicago. Commercial and residential specialists, licensed contractors, free estimates.',
    intro: 'TPO and EPDM are the two most common membrane systems for flat roof replacement in Chicago. Both perform well in the Chicago climate. Our verified contractors install both systems and can help you choose the right option for your building.',
    bodyText: 'TPO (thermoplastic polyolefin) has become the dominant flat roof membrane in Chicago over the past decade. It reflects heat in summer, handles freeze-thaw stress well, and is energy code-compliant. TPO seams are heat-welded, creating a strong monolithic membrane. A TPO system costs $10 to $18 per square foot installed and carries 15 to 20 year manufacturer warranties. EPDM (ethylene propylene diene monomer) is a synthetic rubber membrane that has been used in Chicago since the 1970s. It is more flexible at low temperatures than TPO and is often used on buildings where the simpler installation process matters. EPDM costs slightly less than TPO but typically carries a shorter warranty. Both systems require annual inspection for seam integrity and drain condition. Chicago drainage requirements are strict, and any flat roof replacement must meet current slope and drain specifications.',
    faq: [
      { q: 'Which is better for Chicago, TPO or EPDM?', a: 'Both perform well in Chicago. TPO is more energy-efficient and is the current code-preferred system for new installations. EPDM is a proven system with a long track record in cold climates. Your contractor can recommend based on your building type, existing system, and budget.' },
      { q: 'How much does TPO roof replacement cost in Chicago?', a: 'TPO installation on a Chicago two-flat typically runs $9,000 to $14,000. Larger commercial buildings cost more per project but less per square foot. Free estimates from all listed contractors.' },
      { q: 'How long does a TPO or EPDM roof last in Chicago?', a: 'A properly installed TPO roof lasts 20 to 30 years in Chicago with annual inspection. EPDM lasts 15 to 25 years. Longevity depends heavily on installation quality and drain maintenance.' },
      { q: 'Does Chicago code require a specific flat roof system?', a: 'Chicago energy code requires meeting specific R-value insulation requirements for flat roofs. TPO systems can be paired with rigid insulation to meet these requirements. Your contractor will spec the correct assembly to meet current code.' },
    ],
    nameEs: 'Reemplazo de Techo TPO / EPDM',
    titleEs: 'Reemplazo de Techo Plano TPO y EPDM en Chicago',
    metaDescriptionEs: 'Reemplazo de techo plano TPO y EPDM en Chicago. Especialistas comerciales y residenciales, contratistas con licencia, presupuestos gratuitos.',
    introEs: 'TPO y EPDM son los dos sistemas de membrana más comunes para el reemplazo de techo plano en Chicago. Ambos funcionan bien en el clima de Chicago. Nuestros contratistas verificados instalan ambos sistemas y pueden ayudarle a elegir la opción correcta para su edificio.',
    bodyTextEs: 'El TPO (poliolefina termoplástica) se ha convertido en la membrana de techo plano dominante en Chicago durante la última década. Refleja el calor en verano, maneja bien el estrés de congelación-descongelación y cumple con el código de energía. Las costuras del TPO se sueldan con calor, creando una membrana monolítica resistente. Un sistema TPO cuesta entre $10 y $18 por pie cuadrado instalado y tiene garantías del fabricante de 15 a 20 años. El EPDM (monómero de etileno propileno dieno) es una membrana de caucho sintético que se ha utilizado en Chicago desde la década de 1970. Es más flexible a bajas temperaturas que el TPO y se usa frecuentemente en edificios donde importa el proceso de instalación más simple. El EPDM cuesta un poco menos que el TPO pero generalmente tiene una garantía más corta. Ambos sistemas requieren inspección anual de la integridad de las costuras y el estado del desagüe. Los requisitos de drenaje de Chicago son estrictos y cualquier reemplazo de techo plano debe cumplir con las especificaciones actuales de pendiente y desagüe.',
    faqEs: [
      { q: '¿Cuál es mejor para Chicago, TPO o EPDM?', a: 'Ambos funcionan bien en Chicago. El TPO es más eficiente energéticamente y es el sistema actualmente preferido por el código para nuevas instalaciones. El EPDM es un sistema probado con un largo historial en climas fríos. Su contratista puede recomendar según el tipo de edificio, el sistema existente y el presupuesto.' },
      { q: '¿Cuánto cuesta el reemplazo de techo TPO en Chicago?', a: 'La instalación de TPO en un edificio de dos pisos de Chicago cuesta típicamente entre $9,000 y $14,000. Los edificios comerciales más grandes cuestan más por proyecto pero menos por pie cuadrado. Presupuestos gratuitos de todos los contratistas de la lista.' },
      { q: '¿Cuánto dura un techo TPO o EPDM en Chicago?', a: 'Un techo TPO correctamente instalado dura de 20 a 30 años en Chicago con inspección anual. El EPDM dura de 15 a 25 años. La longevidad depende mucho de la calidad de instalación y el mantenimiento del desagüe.' },
      { q: '¿El código de Chicago requiere un sistema de techo plano específico?', a: 'El código de energía de Chicago requiere cumplir con requisitos específicos de valor R de aislamiento para techos planos. Los sistemas TPO se pueden combinar con aislamiento rígido para cumplir estos requisitos. Su contratista especificará el ensamblaje correcto para cumplir con el código actual.' },
    ],
  },
  {
    slug: 'storm-damage-roof-replacement',
    name: 'Storm Damage Roof Replacement',
    title: 'Storm Damage Roof Replacement Chicago',
    metaDescription: 'Roof replacement after storm damage in Chicago. Hail and wind specialists, insurance claim assistance, licensed contractors, free estimates.',
    intro: 'Chicago gets hit by major hailstorms and wind events every year. When storm damage is extensive enough to require full replacement, homeowner insurance typically covers the cost. Our verified contractors have experience with storm damage assessment and insurance claim documentation.',
    bodyText: 'Storm damage roof replacement in Chicago follows a specific process. After a storm, document damage with photographs within 48 hours. Have a licensed contractor inspect and provide a written damage assessment before calling your insurance company. File the claim with the contractor written assessment in hand. Request that the contractor be present during the insurance adjuster visit. Illinois homeowners typically have 12 to 24 months from the storm date to file a hail damage claim. The most important factor in getting a claim approved is the quality of documentation. Experienced contractors know how to document hail spatter patterns, granule displacement, and structural impact in a way that satisfies insurance adjusters. Hail damage is not always visible from the ground. Small granule bruises and dented metal components require a ladder or drone inspection to properly identify.',
    faq: [
      { q: 'Will insurance cover my roof replacement after a Chicago hailstorm?', a: 'Most homeowner policies cover roof replacement when hail or wind causes sufficient damage. The key is documentation. Get a contractor written assessment before calling your insurer. Insurance covers storm damage, not normal aging.' },
      { q: 'How do I know if my roof was damaged in a Chicago storm?', a: 'Signs include granules in gutters, dented aluminum vents or flashing, bruising on shingles visible from close up, and water stains appearing on interior ceilings after the storm. A free inspection from a licensed contractor is the most reliable way to assess damage.' },
      { q: 'What is the timeline for filing a hail damage claim in Illinois?', a: 'Illinois homeowners typically have 12 to 24 months from the date of a storm to file a hail damage claim. Check your specific policy for exact terms. Do not wait, as documentation becomes harder to confirm as time passes.' },
      { q: 'Should I use a storm chaser contractor after a Chicago hailstorm?', a: 'Be cautious. After major storms, out-of-state contractors flood Chicago neighborhoods. Always verify Illinois IDFPR license before signing anything. Licensed local contractors who will be in business for the warranty period are a safer choice.' },
    ],
    nameEs: 'Reemplazo de Techo por Daños de Tormenta',
    titleEs: 'Reemplazo de Techo por Daños de Tormenta en Chicago',
    metaDescriptionEs: 'Reemplazo de techo después de daños por tormenta en Chicago. Especialistas en granizo y viento, asistencia con reclamos de seguro, contratistas con licencia, presupuestos gratuitos.',
    introEs: 'Chicago es golpeada por grandes tormentas de granizo y eventos de viento cada año. Cuando los daños por tormenta son lo suficientemente extensos como para requerir un reemplazo completo, el seguro de propietario generalmente cubre el costo. Nuestros contratistas verificados tienen experiencia en la evaluación de daños por tormenta y la documentación de reclamos de seguro.',
    bodyTextEs: 'El reemplazo de techo por daños de tormenta en Chicago sigue un proceso específico. Después de una tormenta, documente los daños con fotografías dentro de las 48 horas. Haga que un contratista con licencia inspeccione y proporcione una evaluación escrita de los daños antes de llamar a su compañía de seguros. Presente el reclamo con la evaluación escrita del contratista en mano. Solicite que el contratista esté presente durante la visita del ajustador de seguros. Los propietarios de Illinois generalmente tienen de 12 a 24 meses desde la fecha de la tormenta para presentar un reclamo por daños de granizo. El factor más importante para que un reclamo sea aprobado es la calidad de la documentación. Los contratistas experimentados saben cómo documentar los patrones de salpicadura de granizo, el desplazamiento de gránulos y el impacto estructural de una manera que satisfaga a los ajustadores de seguros. El daño por granizo no siempre es visible desde el suelo. Los pequeños moretones en los gránulos y los componentes de metal abollados requieren una inspección con escalera o dron para identificarlos correctamente.',
    faqEs: [
      { q: '¿El seguro cubrirá el reemplazo de mi techo después de una tormenta de granizo en Chicago?', a: 'La mayoría de las pólizas de propietario cubren el reemplazo del techo cuando el granizo o el viento causan daños suficientes. La clave es la documentación. Obtenga una evaluación escrita del contratista antes de llamar a su aseguradora. El seguro cubre los daños por tormenta, no el envejecimiento normal.' },
      { q: '¿Cómo sé si mi techo fue dañado en una tormenta de Chicago?', a: 'Las señales incluyen gránulos en las canaletas, ventilaciones o tapajuntas de aluminio abollados, moretones en las tejas visibles de cerca y manchas de agua que aparecen en los techos interiores después de la tormenta. Una inspección gratuita de un contratista con licencia es la forma más confiable de evaluar los daños.' },
      { q: '¿Cuál es el plazo para presentar un reclamo por daños de granizo en Illinois?', a: 'Los propietarios de Illinois generalmente tienen de 12 a 24 meses desde la fecha de una tormenta para presentar un reclamo por daños de granizo. Verifique su póliza específica para conocer los términos exactos. No espere, ya que la documentación se vuelve más difícil de confirmar con el tiempo.' },
      { q: '¿Debo usar un contratista cazador de tormentas después de una tormenta de granizo en Chicago?', a: 'Tenga cuidado. Después de las grandes tormentas, contratistas de otros estados inundan los vecindarios de Chicago. Siempre verifique la licencia IDFPR de Illinois antes de firmar cualquier cosa. Los contratistas locales con licencia que estarán en el negocio durante el período de garantía son una opción más segura.' },
    ],
  },
]
